# Generated by Django 4.0.6 on 2022-07-23 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news_page.сategory'),
        ),
    ]
